services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DATA_PASS}
    volumes:
      - dados_postgres:/var/lib/postgresql/data
  api:
    build: ./back-end
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  frontend:
    build: ./front-end
    ports:
      - "8501:8501"
    depends_on:
      - api
    env_file:
      - .env

volumes:
  dados_postgres: